### ISSUE TITLE
wrong chat snippet for `image-text-to-text` task

### ISSUE THREAD

**Issue by not-lain** [huggingface/huggingface.js#1010] opened 2024-11-01 17:28 UTC
the content section has 2 inputs that are dictionaries, and bot of them have have `type` as a key.
what I would suggest is to update only the code snippet and use a `list` in there.
![image](https://github.com/user-attachments/assets/f7b90495-0572-48aa-af4c-e78697f57667)
## fix
![image](https://github.com/user-attachments/assets/e75eb671-3170-4942-ae77-2ac205df0b67)

**Comment by mishig25** [comment] 2024-11-04 10:04
@not-lain thanks a lot for notifying! The issue is being fixed in https://github.com/huggingface/huggingface.js/pull/1003

**Closed** 2024-11-04 15:23 UTC
