### ISSUE TITLE
Safetensors sharded model inspector does not work in subdirs

### ISSUE THREAD

**Issue by madgetr** [huggingface/huggingface.js#588] opened 2024-03-28 21:38 UTC
![image](https://github.com/huggingface/huggingface.js/assets/16808224/f9f72094-67bb-4c97-a52d-52d37ceb9709)
It seems that the model inspector for sharded safetensors does not work when the model is in a sub directory.

**Comment by coyotte508** [comment] 2024-03-28 22:25
cc @mishig25 @julien-c

**Comment by coyotte508** [comment] 2024-03-28 23:25
We have an internal PR open for the hub that should fix it @madgetr (cc @mishig25)

**Comment by mishig25** [comment] 2024-03-28 23:27
Yep it should be fixed by https://github.com/huggingface/huggingface.js/pull/563

the hf.co needs to use latest hf.js

**Comment by coyotte508** [comment] 2024-03-29 11:42
hmm thinking about it the issue is sharded models, and the hub PR is for single-file models I think 

This issue is related to https://github.com/huggingface/huggingface.js/issues/592 I think

**Comment by julien-c** [comment] 2024-03-29 12:06
@madgetr can you provide a link to the model (if it's a public one) you screenshoted that has a `safetensors sharded file inside a subdir`? So we can make sure it works:)

**Comment by madgetr** [comment] 2024-03-29 12:31
https://huggingface.co/Alignment-Lab-AI/ALAI-gemma-7b/tree/main/7b/1

**Closed** 2024-03-29 23:25 UTC

**Comment by mishig25** [comment] 2024-04-02 10:35
thanks a lot for notifying the issue again. The fix is deployed. You can see a working example at: https://huggingface.co/Alignment-Lab-AI/ALAI-gemma-7b/tree/main/7b/1?show_tensors=7b%2F1%2Fmodel.safetensors.index.json

![Screenshot 2024-04-02 at 12 34 23 PM](https://github.com/huggingface/huggingface.js/assets/11827707/8355f070-19f7-40bd-9dfb-578040f67c02)
